export interface SportParam {
  id: string;
  label: string;
}

// Sport-specific fields, matching the columns populated in each sport's
// database sheet. Football gets football facts, Cricket gets cricket facts,
// etc. — no more generic motorsport fields (raceDistance, numberOfTurns...)
// leaking into sports that don't have them.
export const SPORT_SPECIFIC_PARAMS: Record<string, SportParam[]> = {
  'Formula 1': [
    { id: 'dimensions', label: 'Circuit Layout' },
    { id: 'raceDistance', label: 'Race Distance' },
    { id: 'numberOfTurns', label: 'Number of Turns' },
    { id: 'altitude', label: 'Altitude' },
    { id: 'historicRecords', label: 'Historic Records' },
  ],
  Football: [
    { id: 'pitchDimensions', label: 'Pitch Dimensions' },
    { id: 'roofType', label: 'Roof Type' },
    { id: 'recordAttendance', label: 'Record Attendance' },
    { id: 'europeanTitles', label: 'European Titles' },
    { id: 'domesticTitles', label: 'Domestic Titles' },
    { id: 'rivalClub', label: 'Rival Club' },
    { id: 'legendaryManager', label: 'Legendary Manager' },
    { id: 'legendaryPlayer', label: 'Legendary Player' },
    { id: 'clubRecordScorer', label: 'Club Record Scorer' },
    { id: 'floodlightsInstalled', label: 'Floodlights Installed' },
    { id: 'lastRenovation', label: 'Last Renovation' },
    { id: 'safeStandingSection', label: 'Safe Standing Section' },
    { id: 'groundOwnership', label: 'Ground Ownership' },
    { id: 'stadiumTours', label: 'Stadium Tours' },
    { id: 'ticketPriceRange', label: 'Ticket Price Range' },
  ],
  Cricket: [
    { id: 'groundType', label: 'Ground Type' },
    { id: 'endsNames', label: 'Ends' },
    { id: 'highestTestScore', label: 'Highest Test Score' },
    { id: 'mostTestsHosted', label: 'Tests Hosted' },
    { id: 'famousFeature', label: 'Famous Feature' },
    { id: 'pitchType', label: 'Pitch Type' },
    { id: 'dayNightCapable', label: 'Day-Night Capable' },
    { id: 'firstTestYear', label: 'First Test Year' },
    { id: 'domesticTeamResident', label: 'Domestic Team' },
    { id: 'worldCupFinalsHosted', label: 'World Cup Finals Hosted' },
    { id: 'boundaryLength', label: 'Boundary Length' },
    { id: 'clubhouseStyle', label: 'Clubhouse Style' },
    { id: 'recordAttendance', label: 'Record Attendance' },
    { id: 'legendaryPlayer', label: 'Legendary Player' },
  ],
  Tennis: [
    { id: 'surfaceType', label: 'Surface Type' },
    { id: 'grandSlamName', label: 'Grand Slam' },
    { id: 'courtName', label: 'Court Name' },
    { id: 'retractableRoof', label: 'Retractable Roof' },
    { id: 'numberOfCourts', label: 'Number of Courts' },
    { id: 'recordAttendance', label: 'Record Attendance' },
    { id: 'mostTitlesMale', label: 'Most Titles (Male)' },
    { id: 'mostTitlesFemale', label: 'Most Titles (Female)' },
    { id: 'prizeMoneyTotal', label: 'Prize Money' },
    { id: 'firstEditionYear', label: 'First Edition' },
    { id: 'signatureTradition', label: 'Signature Tradition' },
    { id: 'traditionalAttire', label: 'Traditional Attire' },
    { id: 'nightSessionCapable', label: 'Night Session Capable' },
    { id: 'longestMatchRecord', label: 'Longest Match Record' },
    { id: 'queueTradition', label: 'Queue Tradition' },
  ],
  Golf: [
    { id: 'parTotal', label: 'Par' },
    { id: 'courseLength', label: 'Course Length' },
    { id: 'numberOfHoles', label: 'Number of Holes' },
    { id: 'signatureHole', label: 'Signature Hole' },
    { id: 'courseStyle', label: 'Course Style' },
    { id: 'majorChampionship', label: 'Major Championship' },
    { id: 'recordScore', label: 'Record Score' },
    { id: 'legendaryChampion', label: 'Legendary Champion' },
    { id: 'clubhouseStyle', label: 'Clubhouse Style' },
    { id: 'membershipType', label: 'Membership Type' },
    { id: 'notableHazard', label: 'Notable Hazard' },
    { id: 'firstTournamentYear', label: 'First Tournament Year' },
    { id: 'traditionSymbol', label: 'Tradition Symbol' },
    { id: 'greenSpeed', label: 'Green Speed' },
    { id: 'seasonPlayed', label: 'Season Played' },
  ],
  Rugby: [
    { id: 'pitchDimensions', label: 'Pitch Dimensions' },
    { id: 'roofType', label: 'Roof Type' },
    { id: 'recordAttendance', label: 'Record Attendance' },
    { id: 'homeUnion', label: 'Home Union' },
    { id: 'tryLineTradition', label: 'Try Line Tradition' },
    { id: 'grandSlamsWon', label: 'Grand Slams Won' },
    { id: 'worldCupFinalsHosted', label: 'World Cup Finals Hosted' },
    { id: 'rivalryFixture', label: 'Rivalry Fixture' },
    { id: 'famousStand', label: 'Famous Stand' },
    { id: 'floodlightsInstalled', label: 'Floodlights Installed' },
    { id: 'singingTradition', label: 'Singing Tradition' },
    { id: 'firstMatchYear', label: 'First Match Year' },
    { id: 'governingBody', label: 'Governing Body' },
    { id: 'highestScoreRecord', label: 'Highest Score Record' },
    { id: 'legendaryPlayer', label: 'Legendary Player' },
  ],
  'Olympic Venues': [
    { id: 'gamesEdition', label: 'Games Edition' },
    { id: 'eventsHosted', label: 'Events Hosted' },
    { id: 'openingCeremonyHeld', label: 'Opening Ceremony Held' },
    { id: 'closingCeremonyHeld', label: 'Closing Ceremony Held' },
    { id: 'torchCauldronLocation', label: 'Torch Cauldron' },
    { id: 'medalsAwarded', label: 'Medals Awarded' },
    { id: 'legacyUseToday', label: 'Legacy Use Today' },
    { id: 'legendaryAthlete', label: 'Legendary Athlete' },
    { id: 'architecturalStyle', label: 'Architectural Style' },
    { id: 'recordsSetHere', label: 'Records Set Here' },
    { id: 'constructionCost', label: 'Construction Cost' },
    { id: 'capacityDuringGames', label: 'Capacity During Games' },
    { id: 'renovatedSince', label: 'Renovated Since' },
    { id: 'sustainabilityFeatures', label: 'Sustainability Features' },
    { id: 'hostCityLegacy', label: 'Host City Legacy' },
  ],
  Boxing: [
    { id: 'venueType', label: 'Venue Type' },
    { id: 'biggestFightHosted', label: 'Biggest Fight Hosted' },
    { id: 'recordAttendance', label: 'Record Attendance' },
    { id: 'ringSize', label: 'Ring Size' },
    { id: 'legendaryBoxer', label: 'Legendary Boxer' },
    { id: 'titlesDefended', label: 'Titles Defended' },
    { id: 'knockoutRecord', label: 'Knockout Record' },
    { id: 'promoterAssociation', label: 'Promoter Association' },
    { id: 'broadcastHistory', label: 'Broadcast History' },
    { id: 'capacityForBoxing', label: 'Capacity for Boxing' },
    { id: 'firstFightYear', label: 'First Fight Year' },
    { id: 'walkoutTradition', label: 'Walkout Tradition' },
    { id: 'notableRivalry', label: 'Notable Rivalry' },
    { id: 'arenaNickname', label: 'Arena Nickname' },
    { id: 'otherEventsHosted', label: 'Other Events Hosted' },
  ],
};

export function getSportParams(sport: string): SportParam[] {
  return SPORT_SPECIFIC_PARAMS[sport] || [];
}

// Sensible defaults pre-selected on the Parameter Selection screen —
// the 3 facts most likely to make an interesting poster line for each sport.
export const DEFAULT_SPORT_PARAM_IDS: Record<string, string[]> = {
  'Formula 1': ['raceDistance', 'numberOfTurns', 'historicRecords'],
  Football: ['recordAttendance', 'rivalClub', 'legendaryPlayer'],
  Cricket: ['famousFeature', 'mostTestsHosted', 'legendaryPlayer'],
  Tennis: ['courtName', 'signatureTradition', 'mostTitlesMale'],
  Golf: ['signatureHole', 'traditionSymbol', 'legendaryChampion'],
  Rugby: ['tryLineTradition', 'rivalryFixture', 'legendaryPlayer'],
  'Olympic Venues': ['gamesEdition', 'legendaryAthlete', 'legacyUseToday'],
  Boxing: ['biggestFightHosted', 'legendaryBoxer', 'arenaNickname'],
};
